"""为FileModel添加外键

Revision ID: c4ee1b8db17d
Revises: b3e6814df96e
Create Date: 2024-01-07 22:48:35.582238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4ee1b8db17d'
down_revision: Union[str, None] = 'b3e6814df96e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_foreign_key('user_id', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint('user_id', type_='foreignkey')
    # ### end Alembic commands ###
